#!/bin/bash
#
# Kadr — append a release to the Sparkle appcast (docs/04 §10).
#
# Split out of release.sh so a signature can be re-applied without rebuilding, and so the
# appcast can be regenerated by hand if a release needs amending.
set -euo pipefail

cd "$(dirname "$0")/.." || exit 1

VERSION=""
BUILD=""
DMG=""
SIGNATURE_LINE=""
APPCAST="appcast.xml"
REPO="kadr-app/kadr"

while [ $# -gt 0 ]; do
    case "$1" in
        --version) VERSION="$2"; shift 2 ;;
        --build) BUILD="$2"; shift 2 ;;
        --dmg) DMG="$2"; shift 2 ;;
        --signature-line) SIGNATURE_LINE="$2"; shift 2 ;;
        --appcast) APPCAST="$2"; shift 2 ;;
        --repo) REPO="$2"; shift 2 ;;
        *) echo "unknown argument: $1"; exit 2 ;;
    esac
done

[ -n "$VERSION" ] && [ -n "$BUILD" ] && [ -f "$DMG" ] || {
    echo "usage: update-appcast.sh --version X --build N --dmg path [--signature-line '…']"
    exit 2
}

# sign_update prints an attribute fragment; take the signature out of it.
SIGNATURE=$(printf '%s' "$SIGNATURE_LINE" | sed -n 's/.*sparkle:edSignature="\([^"]*\)".*/\1/p')
LENGTH=$(stat -f%z "$DMG")
PUBDATE=$(date -u "+%a, %d %b %Y %H:%M:%S +0000")
URL="https://github.com/$REPO/releases/download/v$VERSION/$(basename "$DMG")"

ITEM=$(cat <<ITEMEOF
    <item>
      <title>Version $VERSION</title>
      <pubDate>$PUBDATE</pubDate>
      <sparkle:version>$BUILD</sparkle:version>
      <sparkle:shortVersionString>$VERSION</sparkle:shortVersionString>
      <sparkle:minimumSystemVersion>14.0</sparkle:minimumSystemVersion>
      <enclosure url="$URL"
                 type="application/octet-stream"
                 sparkle:edSignature="$SIGNATURE"
                 length="$LENGTH" />
    </item>
ITEMEOF
)

# Newest first, which is the order Sparkle expects to read them in.
python3 - "$APPCAST" "$ITEM" <<'PYEOF'
import sys
path, item = sys.argv[1], sys.argv[2]
with open(path) as file:
    contents = file.read()
marker = "    <language>en</language>\n"
if marker not in contents:
    raise SystemExit(f"{path} does not look like Kadr's appcast")
with open(path, "w") as file:
    file.write(contents.replace(marker, marker + item + "\n", 1))
PYEOF

echo "added version $VERSION (build $BUILD) to $APPCAST"
